inventory_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main, create_item, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, \
                        add_item, reduce_item, delete_item, edit_item, get_item_json, add_item_ajax, create_item_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-item', create_item, name='create_item'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('add-item/<int:id>/', add_item, name='add_item'),
    path('reduce-item/<int:id>/', reduce_item, name='reduce_item'),
    path('delete-item/<int:id>/', delete_item, name='delete_item'),
    path('edit-item/<int:id>', edit_item, name='edit_item'),
    path('get-item/', get_item_json, name='get_item_json'),
    path('create-ajax/', add_item_ajax, name='add_item_ajax'),
    path('create-flutter/', create_item_flutter, name='create_item_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    description = models.TextField()

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description"]

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseNotFound, HttpResponseRedirect
from main.forms import ItemForm
from django.urls import reverse
from main.models import Item
from django.http import HttpResponse
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
import datetime

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    if 'last_login' not in request.COOKIES.keys():
        return redirect('main:login')
    
    items = Item.objects.filter(user=request.user)

    context = {
        'appname': 'Inventory Manager',
        'name': request.user.username,
        'class': 'PBP A',
        'items': items,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_item.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_item(request, id):
    # Get product berdasarkan ID
    item = Item.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_item.html", context)

def get_item_json(request):
    product_item = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_item_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_item = Item(name=name, amount=amount, description=description, user=user)
        new_item.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def add_item(request, id):
    if request.method == "POST":
        item = Item.objects.get(pk=id)
        item.amount += 1;
        item.save()

        return HttpResponse(b"ADDED", status=201)
    
    return HttpResponseNotFound()

@csrf_exempt
def reduce_item(request, id):
    if request.method == "POST":
        item = Item.objects.get(pk=id)
        if item.amount > 1:
            item.amount -= 1;
            item.save()
        else:
            item.delete()
        
        return HttpResponse(b"REDUCED", status=201)
    
    return HttpResponseNotFound()

@csrf_exempt
def delete_item(request, id):
    if request.method == "POST":
        item = Item.objects.get(pk=id)
        item.delete()

        return HttpResponse(b"DELETED", status=201)
    
    return HttpResponseNotFound()

@csrf_exempt
def create_item_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_item = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            description = data["description"]
        )

        new_item.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_item.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Item"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/edit_item.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<nav class="navbar navbar-expand justify-content-center" style="background-color: #00796B;">
    <h1>Edit Item</h1>
</nav>

<div class="h-100 d-flex align-items-center justify-content-center" style="margin-top: 100px;">
    <form method="POST">  
        {% csrf_token %}  
        <table style="justify-items: center;">  
            {{ form.as_table }}  
            <tr>  
                <td></td>
                <td><input type="submit" value="Add Item" class="btn btn-success"></td>  
            </tr>  
        </table>    
    </form>
</div>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
<nav class="navbar navbar-expand justify-content-center" style="background-color: #00796B;"">
    <h1>Inventory Manager</h1>
</nav>

<section>
    <div class="container mt-5 pt-5">
        <div class="row">
            <div class="col-12 col-sm-8 col-md-6 m-auto">
                <div class="card">
                    <div class="card-body">
                        <form method="POST" action="">
                            {% csrf_token %}
                            <input type="text" name="username" id="" class="form-control my-3 py-2" placeholder="Username">
                            <input type="password" name="password" id="" class="form-control my-3 py-2" placeholder="Password">
                            <div class="text-center">
                                <input class="btn btn-success" type="submit" value="Login" style="margin-top: 20px; margin-bottom: 20px;">
                            </div>

                            {% if messages %}
                                <ul>
                                {% for message in messages %}
                                    <li>{{ message }}</li>
                                {% endfor %}
                                </ul>
                            {% endif %}

                            <div class="text-center">
                                Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block meta %}
    <style>
        .item-actions {
            display: flex;
            align-items: center;
            gap: 10;
        }
        .container {
            text-align: center;
        }
        .main {
            padding-top: 30px;
        }
        .footer {
            margin-top: 40px;
        }
        .btn-add-item {
            margin-left: 10px;
            margin-left: 10px;
            margin-bottom: 30px;
        }
        .card {
            box-shadow: rgba(0, 0, 0, 0.25) 0px 0.0625em 0.0625em, rgba(0, 0, 0, 0.25) 0px 0.125em 0.5em, rgba(255, 255, 255, 0.1) 0px 0px 0px 1px inset;
        }
    </style>
{% endblock meta %}

{% block content %}

    <nav class="navbar navbar-expand" style="background-color: #00796B;">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">{{ appname }}</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                </ul>
            
            <div class="dropdown">
                <button class="btn btn-danger dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{ name }}
                </button>
                <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'main:logout' %}">Logout</a></li>
                </ul>
            </div>

        </div>
    </nav>    

    <div class="container main">
    
        <div class="container">
            <p id="items-count">Kamu menyimpan {{ items|length }} item pada aplikasi ini</p>
        </div>
        
        <a href="{% url 'main:create_item' %}" class="btn link-success btn-success btn-add-item" style="background-color: #B2DFDB;">
            Add New Item
        </a>
        
        <button type="button" class="btn btn-primary btn-add-item" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product by AJAX</button>
        
        {% if items %}
        <div class="container" id="item-content"></div>
        {% endif %}
    
    
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" class="form-control" id="name" name="name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="price" class="col-form-label">Amount:</label>
                            <input type="number" class="form-control" id="amount" name="amount"></input>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="description" name="description"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
                </div>
            </div>
        </div>
    </div>

    <div class="footer">
        <div class="text-success"><hr></div>
        <p class="font-monospace" style="font-size: small;">Sesi terakhir login: {{ last_login }}</p>
    </div>

    <script>
        async function getItems() {
            return fetch("{% url 'main:get_item_json' %}").then((res) => res.json())
        }

        function incrementItem(itemId) {
            fetch("{% url 'main:add_item' id=1 %}".replace(/1/, itemId), {
                method: "POST",
            }).then(refreshItems)

            return false
        }

        function reduceItem(itemId) {
            fetch("{% url 'main:reduce_item' id=1 %}".replace(/1/, itemId), {
                method: "POST",
            }).then(refreshItems)

            return false
        }

        function deleteItem(itemId) {
            fetch("{% url 'main:delete_item' id=1 %}".replace(/1/, itemId), {
                method: "POST",
            }).then(refreshItems)

            return false
        }

        async function refreshItems() {
            document.getElementById("item-content").innerHTML = ""
            const items = await getItems()
            var itemsCount = items.length
            let itemsCountString = ``
            if (itemsCount == 0) {
                itemsCountString = `Kamu belum menyimpan item apa pun pada aplikasi ini`
            } else {
                itemsCountString = `Kamu menyimpan ${itemsCount} item pada aplikasi ini`
            }
            document.getElementById("items-count").innerHTML = itemsCountString
            let htmlString = ``
            items.forEach((item) => {
                var editItemURL = "{% url 'main:edit_item' id=1 %}".replace(/1/, item.pk.toString());
                var itemId = item.pk
                htmlString += `
                <div class="card text-start border-dark mb-3" style="max-width: 18rem;display: inline-block;margin: 1%;width: 300px;">
                    <div class="card-body" style="height: 200px;">
                        <h5 class="card-title">${item.fields.name}</h5>
                        <div class="overflow-y-auto" style="max-height: 120px;">${item.fields.description}</div>                   
                    </div>
                    <div class="card-footer">
                        <div class="d-flex justify-content-between align-items-center">
                            <div><span class="badge text-bg-secondary">${item.fields.amount}</span></div>
                            <div class="d-flex">
                                <button data-item-id="${itemId}" type="button" class="btn btn-outline-success btn-sm increment-button" style="margin-right: 7px; width: 2rem;">+</button>                             
                                <button data-item-id="${itemId}" type="button" class="btn btn-outline-warning btn-sm reduce-button" style="margin-right: 7px; width: 2rem;">-</button>                         
                                <a href="${editItemURL}">
                                    <button data-item-id="${itemId}" type="button" class="btn btn-outline-primary btn-sm" style="margin-right: 7px; width: 2rem;"><i class="bi bi-pencil"></i></button>
                                </a>
                                <button data-item-id="${itemId}" type="button" class="btn btn-outline-danger btn-sm delete-button" style="margin-right: 7px; width: 2rem;"><i class="bi bi-trash"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
                `
                
                
            })
            document.getElementById("item-content").innerHTML = htmlString

            const incrementButtons = document.getElementsByClassName("increment-button")
            for (var i = 0; i < incrementButtons.length; i++) {
                (function(j) {
                    incrementButtons[j].addEventListener("click", function() {
                        incrementItem(this.getAttribute("data-item-id"));
                    })
                })(i);
            }

            const reduceButtons = document.getElementsByClassName("reduce-button")
            for (var i = 0; i < reduceButtons.length; i++) {
                (function(j) {
                    reduceButtons[j].addEventListener("click", function() {
                        reduceItem(this.getAttribute("data-item-id"));
                    })
                })(i);
            }

            const deleteButtons = document.getElementsByClassName("delete-button")
            for (var i = 0; i < deleteButtons.length; i++) {
                (function(j) {
                    deleteButtons[j].addEventListener("click", function() {
                        deleteItem(this.getAttribute("data-item-id"));
                    })
                })(i);
            }
        }

        refreshItems()

        function addItem() {
            fetch("{% url 'main:add_item_ajax' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshItems)

            document.getElementById("form").reset()
            return false
        }
        document.getElementById("button_add").onclick = addItem
    </script>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>

{% endblock meta %}

{% block content %}
<nav class="navbar navbar-expand justify-content-center" style="background-color: #00796B;">
    <h1>Inventory Manager</h1>
</nav>

<div class="h-100 d-flex align-items-center justify-content-center" style="margin-top: 100px;">
    <form method="POST">  
        {% csrf_token %}  
        <table style="justify-items: center;">  
            {{ form.as_table }}  
            <tr>  
                <td></td>
                <td><input type="submit" name="submit" value="Daftar" class="btn btn-success"></td>  
            </tr>  
        </table>  
    </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}
</div>

{% endblock content %}